CREATE PROCEDURE scpCrearCompra (
	@ID_CLIENTE INT,
	@ID_COMPRA INT,
	@ID_PLAN_SEPARE INT,
	@ID_PROMOCION INT,
	@CEDULA VARCHAR(20),
	@NOMBRE VARCHAR(50),
	@DIRECCION VARCHAR(100),
	@VALOR NUMERIC(18, 2),
	@CANTIDAD INT,
	@ID_PRODUCTO INT
	)
AS
BEGIN
	IF(@ID_CLIENTE = 0)
	BEGIN
		INSERT INTO CLIENTE(CEDULA, NOMBRE, DIRECCION)
		VALUES (@CEDULA, @NOMBRE, @DIRECCION)

		SELECT @ID_CLIENTE = MAX(ID_CLIENTE) FROM CLIENTE
		SELECT @ID_PLAN_SEPARE = MAX(ID_PLAN_SEPARE) FROM PLAN_SEPARE
		SELECT @ID_PROMOCION = MAX(ID_PROMOCION) FROM PROMOCIONES

		INSERT INTO COMPRA(FECHA, VALOR, ID_PLAN_SEPARE, ID_PROMOCION, ID_CLIENTE)
		VALUES(GETDATE(), @VALOR, @ID_PLAN_SEPARE, @ID_PROMOCION, @ID_CLIENTE)

		SELECT @ID_COMPRA = MAX(ID_COMPRA) FROM COMPRA WHERE ID_CLIENTE = @ID_CLIENTE

		INSERT INTO DETALLE_COMPRA(CANTIDAD, ID_COMPRA, ID_PRODUCTO)
		VALUES(@CANTIDAD, @ID_COMPRA, @ID_PRODUCTO)
	END
	ELSE
	BEGIN
		UPDATE CLIENTE
		SET
		CEDULA = @CEDULA, 
		NOMBRE = @NOMBRE, 
		DIRECCION = @DIRECCION
		WHERE ID_CLIENTE = @ID_CLIENTE

		SELECT @ID_PLAN_SEPARE = MAX(ID_PLAN_SEPARE) FROM PLAN_SEPARE
		SELECT @ID_PROMOCION = MAX(ID_PROMOCION) FROM PROMOCIONES

		UPDATE COMPRA 
		SET
		VALOR = @VALOR,
		ID_PLAN_SEPARE = @ID_PLAN_SEPARE,
		ID_PROMOCION = @ID_PROMOCION
		WHERE ID_COMPRA = @ID_COMPRA

		UPDATE DETALLE_COMPRA
		SET
		CANTIDAD = @CANTIDAD,
		ID_PRODUCTO = @ID_PRODUCTO
		WHERE ID_COMPRA = @ID_COMPRA
	END
END