CREATE PROCEDURE scpEliminarCompra(
	@ID_CLIENTE INT 
) 
AS
BEGIN
	DECLARE @ID_COMPRA INT
	SELECT @ID_COMPRA = MAX(ID_COMPRA) FROM COMPRA WHERE ID_CLIENTE = @ID_CLIENTE

	DELETE FROM DETALLE_COMPRA WHERE ID_COMPRA = @ID_COMPRA
	DELETE FROM COMPRA WHERE ID_COMPRA = @ID_COMPRA
	DELETE FROM CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE
END