CREATE PROCEDURE scpObtenerCompras 
AS
BEGIN
	SELECT 
	C.ID_CLIENTE AS 'ID_CLIENTE',
	C.NOMBRE AS 'NOMBRE_CLIENTE',
	C.CEDULA AS 'CEDULA',
	C.DIRECCION AS 'DIRECCION',
	CO.ID_COMPRA AS 'ID_COMPRA',
	CO.FECHA AS 'FECHA',
	CO.VALOR AS 'VALOR',
	PS.ID_PLAN_SEPARE AS 'ID_PLAN_SEPARE',
	PS.PLAN_SEPARE AS 'PLAN_SEPARE',
	PRO.ID_PROMOCION AS 'ID_PROMOCION',
	PRO.PORCENTAJE AS 'PORCENTAJE',
	DC.ID_DETALLE_COMPRA AS 'ID_DETALLE_COMPRA',
	DC.CANTIDAD AS 'CANTIDAD',
	DC.ID_PRODUCTO AS 'ID_PRODUCTO',
	P.NOMBRE AS 'NOMBRE_PRODUCTO'
	FROM 
	CLIENTE C
	INNER JOIN COMPRA CO ON CO.ID_CLIENTE = C.ID_CLIENTE
	INNER JOIN PLAN_SEPARE PS ON PS.ID_PLAN_SEPARE = CO.ID_PLAN_SEPARE
	INNER JOIN PROMOCIONES PRO ON PRO.ID_PROMOCION = CO.ID_PROMOCION
	INNER JOIN DETALLE_COMPRA DC ON DC.ID_COMPRA = CO.ID_COMPRA
	INNER JOIN PRODUCTO P ON P.ID_PRODUCTO = DC.ID_PRODUCTO
END