CREATE PROCEDURE scpObtenerProductos 
AS
BEGIN
	SELECT 
	P.ID_PRODUCTO AS 'ID_PRODUCTO',
	P.NOMBRE AS 'NOMBRE_PRODUCTO',
	P.PRECIO AS 'PRECIO_PRODUCTO',
	T.ID_TALLA AS 'ID_TALLA',
	T.TALLA AS 'TALLA',
	C.ID_COLOR AS 'ID_COLOR',
	C.COLOR AS 'COLOR',
	TD.ID_TIPO_DEPARTAMENTO AS 'ID_TIPO_DEPARTAMENTO',
	TD.DEPARTAMENTO AS 'DEPARTAMENTO'
	FROM 
	PRODUCTO P
	INNER JOIN TALLA T ON T.ID_TALLA = P.ID_TALLA
	INNER JOIN COLOR C ON C.ID_COLOR = P.ID_COLOR
	INNER JOIN TIPO_DEPARTAMENTO TD ON TD.ID_TIPO_DEPARTAMENTO = P.ID_TIPO_DEPARTAMENTO
END